name: "CI"

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v15
      with:
          extra_nix_config: |
              access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: nix develop --no-update-lock-file -c home-build
    - run: ls ./result
